// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcdbfaxlhyxpaqjlevhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jZGJmYXhsaHl4cGFxamxldmhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMzc1OTEsImV4cCI6MjA1OTkxMzU5MX0.BrnFhKdpJTnhmX9Vk2XcNSi42K1nSJtletVMrcJkklA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);